# Generated by Django 5.2.8 on 2025-12-05 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annee_universitaire', '0001_initial'),
        ('etudiant', '0003_etudiant_genre'),
        ('niveau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('Etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='etudiant.etudiant')),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annees', to='annee_universitaire.anneeuniversitaire')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='niveau.niveau')),
            ],
        ),
    ]
