# Generated by Django 5.2.8 on 2025-12-05 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annee_universitaire', '0001_initial'),
        ('etudiant', '0003_etudiant_genre'),
        ('inscription', '0001_initial'),
        ('niveau', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='Etudiant',
        ),
        migrations.AlterField(
            model_name='inscription',
            name='annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='annee_universitaire.anneeuniversitaire'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='niveau.niveau'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='etudiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='etudiant.etudiant'),
        ),
    ]
