# Generated by Django 5.2.8 on 2025-12-04 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('designation', models.CharField()),
                ('created', models.DateField(auto_now_add=True)),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etablissements', to='universite.universite')),
            ],
        ),
    ]
