# Generated by Django 5.2.8 on 2025-12-04 09:00

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=528)),
            ],
        ),
    ]
