# Generated by Django 5.2.8 on 2025-12-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0002_etudiant_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='genre',
            field=models.CharField(default='H', max_length=2),
        ),
    ]
