# Generated by Django 5.2.8 on 2025-12-05 10:03

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0005_alter_etudiant_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
    ]
