# Generated by Django 5.2.8 on 2025-12-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('designation', models.CharField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
