# Generated by Django 5.2.8 on 2025-12-04 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0001_initial'),
        ('mention', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mention',
            name='universite',
        ),
        migrations.AddField(
            model_name='mention',
            name='etablissement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='etablissement.etablissement'),
        ),
    ]
